sections:
  -
    title: 'Learning Ruby'
    summary: 'I want to learn more about specific methods'
    tags:
      - map
  -
    title: 'Setting up Capybara'
    summary: 'I want to get do end to end testing'
    tags:
      - capybara
  -
    title: 'Learning Rake'
    summary: "Rake is a great tool and I've wanted to get better at it."
    tags:
      - rake

ignore:
  words:
    - merge
    - fix
    - typo

